# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2019
version: '{build}'

branches:
  only:
    - main
    - v7

platform: x86
clone_depth: 5
build: off
deploy: off
cache:
  - "%LOCALAPPDATA%\\Yarn"

environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: '14'
    - nodejs_version: '15'

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - yarn run all
  - yarn run test:all
  - yarn run check:all
